version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
    labels:
      - dependencies
    open-pull-requests-limit: 5

  # Lambda Node.js dependencies
  - package-ecosystem: npm
    directory: /self_hosted_runner/lambda_code_folder
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
    labels:
      - dependencies
    open-pull-requests-limit: 5
