name: eks_dev

on:
  push:
    branches:
      - main
    paths:
      - 'dev/eks/**'
      - '.github/workflows/eks_dev.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'dev/eks/**'
      - '.github/workflows/eks_dev.yml'
  workflow_dispatch:
    inputs:
      destroy:
        description: 'Destroy resources?'
        required: true
        type: boolean
        default: false

concurrency:
  group: eks_dev
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    uses: ./.github/workflows/terraform-dev.yml
    with:
      working_directory: dev/eks
      tf_version: '1.13.0'
      skip_check: 'CKV_AWS_58,CKV_AWS_39,CKV_AWS_37,CKV_AWS_38,CKV_AWS_290,CKV_AWS_355'
      destroy: ${{ github.event.inputs.destroy == 'true' }}
    secrets: inherit