name: s3_bucket
on:
  push:
    branches:
      - main
    paths:
      - 's3_bucket/**'
      - '.github/workflows/s3_bucket.yml'
  pull_request:
    branches:
      - main
    paths:
      - 's3_bucket/**'
      - '.github/workflows/s3_bucket.yml'
  workflow_dispatch:

concurrency:
  group: s3_bucket
  cancel-in-progress: true

permissions:       
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      working_directory: s3_bucket
      tf_version: '1.13.0'
      skip_check: 'CKV2_AWS_62,CKV_AWS_145,CKV_AWS_144,CKV_AWS_19'
    secrets: inherit