name: service control policy
on:
  push:
    branches:
      - main
    paths:
      - 'scp/**'
      - '.github/workflows/scp.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'scp/**'
      - '.github/workflows/scp.yml'
  workflow_dispatch:

concurrency:
  group: scp
  cancel-in-progress: true

permissions:       
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      working_directory: scp
      tf_version: '1.13.0'
      skip_check: 'CKV2_AWS_62,CKV_AWS_145,CKV_AWS_144,CKV_AWS_19'
    secrets: inherit
    ##